"""Make orders and products consistent

Revision ID: 58439fbb125b
Revises: baa73dda301f
Create Date: 2025-02-02 20:10:08.953262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58439fbb125b"
down_revision: Union[str, None] = "baa73dda301f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_details", sa.Column("quantity", sa.Integer(), nullable=False))
    op.add_column("order_details", sa.Column("subtotal", sa.Integer(), nullable=False))
    op.add_column("products", sa.Column("currency", sa.String(), nullable=False))
    op.alter_column("products", "reorder_ammount", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "reorder_ammount", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("order_details", "subtotal")
    op.drop_column("order_details", "quantity")
    # ### end Alembic commands ###
