"""your migration title

Revision ID: 7390886b9a78
Revises: baa73dda301f
Create Date: 2025-01-23 19:56:28.710790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7390886b9a78'
down_revision: Union[str, None] = 'baa73dda301f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'reorder_ammount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'reorder_ammount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
