"""add tracking_status to order

Revision ID: 78a7f4c4b8ee
Revises: 6a54a886a8bb
Create Date: 2025-01-12 16:11:13.489609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a7f4c4b8ee'
down_revision: Union[str, None] = '6a54a886a8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tracking_status')
    # ### end Alembic commands ###
