"""add reorder ammount to product

Revision ID: baa73dda301f
Revises: 78a7f4c4b8ee
Create Date: 2025-01-21 12:41:25.574274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa73dda301f'
down_revision: Union[str, None] = '78a7f4c4b8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reorder_ammount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reorder_ammount')
    # ### end Alembic commands ###
