version: "3.8"

services:
  postgresdb:
    image: postgres:14.2
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: ${POSTGRESQL_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_DB_PASS}
      POSTGRES_DB: webshopdb
    volumes:
      - "postgresql:/var/lib/postgresql/data"

    profiles: [dev]

volumes:
  postgresql: {}
